# =========================================================================
# codemagic.yaml - Pipeline CI/CD para Flutter (Corregido para subcarpeta)
# =========================================================================

workflows:
  # -----------------------------------------------------------------------
  # WORKFLOW 1: Pipeline de desarrollo (CI) eeee
  # -----------------------------------------------------------------------
  flutter-ci:
    name: Flutter CI Pipeline
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FLUTTER_WEB: "true"
      
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'develop'
          include: true
        - pattern: 'feature/*'
          include: true
      cancel_previous_builds: true
          
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $FLUTTER_ROOT/.pub-cache
        
    scripts:
      - name: Obtener dependencias de Flutter
        working_directory: demo_app
        script: |
          flutter pub get
          
      - name: Analizar código (lint)
        working_directory: demo_app
        script: |
          flutter analyze --no-fatal-infos
        ignore_failure: true
        
      - name: Verificar formato
        working_directory: demo_app
        script: |
          dart format --set-exit-if-changed lib/
        ignore_failure: true
        
      - name: Ejecutar tests unitarios
        working_directory: demo_app
        script: |
          flutter test --coverage --machine > test-results.json
        test_report: demo_app/test-results.json
        
      - name: Build Android APK (Debug)
        working_directory: demo_app
        script: |
          flutter build apk --debug
          
    artifacts:
      - demo_app/build/**/outputs/**/*.apk
      - demo_app/coverage/lcov.info
      - demo_app/test-results.json
      
    publishing:
      email:
        recipients:
          - equipo@example.com
        notify:
          success: false
          failure: true

  # -----------------------------------------------------------------------
  # WORKFLOW 2: Pipeline de release (CD)
  # -----------------------------------------------------------------------
  flutter-release:
    name: Flutter Release Pipeline
    max_build_duration: 90
    instance_type: mac_mini_m1
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - google_play_credentials
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.example.app"
        
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*'
          include: true
          
    scripts:
      - name: Obtener dependencias
        working_directory: demo_app
        script: flutter pub get
        
      - name: Ejecutar tests
        working_directory: demo_app
        script: flutter test
        
      - name: Build Android App Bundle
        working_directory: demo_app
        script: |
          VERSION=$(echo $CM_TAG | sed 's/v//')
          BUILD_NUMBER=$((PROJECT_BUILD_NUMBER))
          
          flutter build appbundle \
            --release \
            --build-name=$VERSION \
            --build-number=$BUILD_NUMBER
            
      - name: Build iOS IPA
        working_directory: demo_app
        script: |
          VERSION=$(echo $CM_TAG | sed 's/v//')
          BUILD_NUMBER=$((PROJECT_BUILD_NUMBER))
          
          flutter build ipa \
            --release \
            --build-name=$VERSION \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
            
    artifacts:
      - demo_app/build/**/outputs/**/*.aab
      - demo_app/build/ios/ipa/*.ipa
      
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
      email:
        recipients:
          - releases@example.com
        notify:
          success: true
          failure: true

  # -----------------------------------------------------------------------
  # WORKFLOW 3: Pipeline solo para tests (Pull Requests)
  # -----------------------------------------------------------------------
  flutter-tests:
    name: Flutter Tests Only
    max_build_duration: 30
    instance_type: linux_x2
    
    environment:
      flutter: stable
      
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          
    scripts:
      - name: Obtener dependencias
        working_directory: demo_app
        script: flutter pub get
        
      - name: Analizar código
        working_directory: demo_app
        script: flutter analyze
        
      - name: Ejecutar tests con cobertura
        working_directory: demo_app
        script: |
          flutter test --coverage
          
    artifacts:
      - demo_app/coverage/**