# =========================================================================
# codemagic.yaml - Pipeline CI/CD para Flutter
# =========================================================================
# Este fichero define los workflows de CI/CD para Codemagic.
# Debe ubicarse en la raíz del repositorio.
#
# Documentación: https://docs.codemagic.io/yaml-basic-configuration/yaml-getting-started/
# =========================================================================

workflows:
  # -----------------------------------------------------------------------
  # WORKFLOW 1: Pipeline de desarrollo (CI)
  # -----------------------------------------------------------------------
  flutter-ci:
    name: Flutter CI Pipeline
    max_build_duration: 60  # minutos
    instance_type: mac_mini_m1  # mac_mini_m1, mac_pro, linux
    
    # Configuración del entorno
    environment:
      flutter: stable        # stable, beta, master o versión específica
      xcode: latest          # Solo para builds iOS
      cocoapods: default     # Gestor de dependencias iOS
      vars:
        FLUTTER_WEB: "true"  # Variables personalizadas
      
    # Triggers automáticos
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'develop'
          include: true
        - pattern: 'feature/*'
          include: true
      cancel_previous_builds: true  # Cancela builds anteriores si hay nuevo push
          
    # Caché para acelerar builds
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $FLUTTER_ROOT/.pub-cache
        
    # Scripts del pipeline
    scripts:
      # Paso 1: Obtener dependencias
      - name: Obtener dependencias de Flutter
        script: |
          flutter pub get
          
      # Paso 2: Análisis estático de código
      - name: Analizar código (lint)
        script: |
          flutter analyze --no-fatal-infos
        ignore_failure: true  # No falla el build si hay warnings
        
      # Paso 3: Verificar formato de código
      - name: Verificar formato
        script: |
          dart format --set-exit-if-changed lib/
        ignore_failure: true
        
      # Paso 4: Ejecutar tests unitarios
      - name: Ejecutar tests unitarios
        script: |
          flutter test --coverage --machine > test-results.json
        test_report: test-results.json
        
      # Paso 5: Build Android (Debug para CI)
      - name: Build Android APK (Debug)
        script: |
          flutter build apk --debug
          
    # Artefactos generados
    artifacts:
      - build/**/outputs/**/*.apk
      - coverage/lcov.info
      - test-results.json
      
    # Notificaciones
    publishing:
      email:
        recipients:
          - equipo@example.com
        notify:
          success: false   # No notificar en éxito
          failure: true    # Notificar en fallo

  # -----------------------------------------------------------------------
  # WORKFLOW 2: Pipeline de release (CD)
  # -----------------------------------------------------------------------
  flutter-release:
    name: Flutter Release Pipeline
    max_build_duration: 90
    instance_type: mac_mini_m1
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - google_play_credentials  # Grupo de variables en Codemagic
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.example.app"
        
    # Solo se ejecuta en tags de versión
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*'  # v1.0.0, v2.1.0, etc.
          include: true
          
    scripts:
      - name: Obtener dependencias
        script: flutter pub get
        
      - name: Ejecutar tests
        script: flutter test
        
      # Build Android Release
      - name: Build Android App Bundle
        script: |
          # Versión desde el tag (ej: v1.2.3 -> 1.2.3)
          VERSION=$(echo $CM_TAG | sed 's/v//')
          BUILD_NUMBER=$((PROJECT_BUILD_NUMBER))
          
          flutter build appbundle \
            --release \
            --build-name=$VERSION \
            --build-number=$BUILD_NUMBER
            
      # Build iOS Release
      - name: Build iOS IPA
        script: |
          VERSION=$(echo $CM_TAG | sed 's/v//')
          BUILD_NUMBER=$((PROJECT_BUILD_NUMBER))
          
          flutter build ipa \
            --release \
            --build-name=$VERSION \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
            
    artifacts:
      - build/**/outputs/**/*.aab
      - build/ios/ipa/*.ipa
      
    publishing:
      # Publicar a Google Play (Internal Track)
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
        
      # Publicar a App Store Connect (TestFlight)
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        
      # Notificaciones
      email:
        recipients:
          - releases@example.com
        notify:
          success: true
          failure: true

  # -----------------------------------------------------------------------
  # WORKFLOW 3: Pipeline solo para tests (Pull Requests)
  # -----------------------------------------------------------------------
  flutter-tests:
    name: Flutter Tests Only
    max_build_duration: 30
    instance_type: linux_x2  # Más económico para solo tests
    
    environment:
      flutter: stable
      
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          
    scripts:
      - name: Obtener dependencias
        script: flutter pub get
        
      - name: Analizar código
        script: flutter analyze
        
      - name: Ejecutar tests con cobertura
        script: |
          flutter test --coverage
          # Generar reporte HTML (opcional)
          # genhtml coverage/lcov.info -o coverage/html
          
    artifacts:
      - coverage/**
